-- MySQL Script generated by MySQL Workbench
-- Mon Mar 14 18:36:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coffeeshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coffeeshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffeeshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `coffeeshop` ;

-- -----------------------------------------------------
-- Table `coffeeshop`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffeeshop`.`list` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coffeeshop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffeeshop`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `username` VARCHAR(500) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `phone` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coffeeshop`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffeeshop`.`cart` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `list_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cart_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Cart_List1_idx` (`list_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cart_List1`
    FOREIGN KEY (`list_id`)
    REFERENCES `coffeeshop`.`list` (`id`),
  CONSTRAINT `fk_Cart_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffeeshop`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coffeeshop`.`detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffeeshop`.`detail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `date_in` DATETIME NOT NULL,
  `date_out` DATETIME NOT NULL,
  `brand` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `description` VARCHAR(500) CHARACTER SET 'utf8' NOT NULL DEFAULT 'null',
  `list_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detail_list1_idx` (`list_id` ASC) VISIBLE,
  CONSTRAINT `fk_detail_list1`
    FOREIGN KEY (`list_id`)
    REFERENCES `coffeeshop`.`list` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coffeeshop`.`list_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffeeshop`.`list_order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL DEFAULT 'Delivery',
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coffeeshop`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffeeshop`.`profile` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffeeshop`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coffeeshop`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffeeshop`.`rating` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `rate` INT(11) NOT NULL DEFAULT '5',
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rating_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_rating_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffeeshop`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coffeeshop`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffeeshop`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `coffeeshop`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffeeshop`.`user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Role_User_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_User_Role_Role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role_Role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `coffeeshop`.`role` (`id`),
  CONSTRAINT `fk_User_Role_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffeeshop`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
